allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  sharp: true
  unrs-resolver: true
overrides:
  '@parcel/watcher>picomatch': 4.0.4
  nanoid: 3.3.18
  postcss: 8.5.23
  sharp: 0.35.4
  fflate: 0.8.3
